main/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^', include('resume.urls')),

]

resume/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from resume import views
from django import forms
from django.conf import settings

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$',  views.HomeView.as_view(), name = 'home'),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^login/$',  views.Login.as_view(), name = 'login'),
    url(r'^logout/$',  views.LogOut.as_view(), name = 'logout'),
    url(r'^change_info/(?P<pk>\d+)/$',  views.UserView.as_view(), name = 'change_info'),
    url(r'^change_info/(?P<pk>\d+)/del_user/$',  views.UserDelete.as_view(), name = 'del_user'),
    url(r'^contact/$',  views.contactView, name = 'contact'),
    url(r'^info/$',  views.InfoView.as_view(), name = 'info'),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT,}),
    url(r'^static/(?P<path>.*)', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT,}),
    
]

resume/models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser
from captcha.fields import CaptchaField
from django.db.models.fields import CharField
from django.utils.translation import ugettext_lazy as _

from forms import UAPhoneNumberField


class PhoneNumberField(CharField):

    description = _("Ukrainian phone number")

    def __init__(self, *args, **kwargs):
        kwargs['max_length'] = 17
        super(PhoneNumberField, self).__init__(*args, **kwargs)

    def formfield(self, **kwargs):
        defaults = {'form_class': UAPhoneNumberField}
        defaults.update(kwargs)
        return super(PhoneNumberField, self).formfield(**defaults)


class MyUserManager(BaseUserManager):
    def create_user(self, name, first_name, last_name, phone_number, email, date_of_birth, password=None):
        """
        Creates and saves a User with the given email, date of
        birth and password.
        """
        if not name:
            raise ValueError('Users must have a name')

        user = self.model(
            name=name,
            first_name=first_name,
            last_name=last_name,
            email=email,
            date_of_birth=date_of_birth,
            phone_number=phone_number,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, name, first_name, last_name, phone_number, email, date_of_birth, password):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(name, first_name=first_name, last_name=last_name, 
            phone_number=phone_number, email=email, 
            password=password, date_of_birth=date_of_birth
        )
        user.is_admin = True
        user.save(using=self._db)
        return user


class MyUser(AbstractBaseUser):
    name = models.CharField(max_length=40, unique=True)
    first_name = models.CharField(max_length=40)
    last_name = models.CharField(max_length=40)
    email = models.EmailField(max_length=255)
    date_of_birth = models.DateField()
    phone_number = PhoneNumberField()
    avatar = models.ImageField(upload_to = 'media/', default="avatar.png")
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    date_joined = models.DateTimeField(auto_now=True)

    objects = MyUserManager()

    USERNAME_FIELD = 'name'
    REQUIRED_FIELDS = ['email', 'phone_number', 'date_of_birth', 'first_name', 'last_name', 'avatar']

    def get_full_name(self):
        # The user is identified by their email address
        return self.name

    def get_short_name(self):
        # The user is identified by their email address
        return self.name

    def __str__(self):              # __unicode__ on Python 2
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin

resume/forms.py
from django import forms
from captcha.fields import CaptchaField
import re

from django.forms.fields import CharField
from django.core.validators import EMPTY_VALUES
from django.forms import ValidationError
from django.utils.translation import ugettext_lazy as _


phone_digits = re.compile(r'^\d{3}[-]\d{7}$')


class UAPhoneNumberField(CharField):
    default_error_messages = {
        'invalid': _('Phone numbers must be in 0XX-XXXXXXX format.'),
    }

    def clean(self, value):
        super(UAPhoneNumberField, self).clean(value)
        if value in EMPTY_VALUES:
            return u''
        match = phone_digits.match(value)
        if match:
            return value
        raise ValidationError(self.error_messages['invalid'])

class CaptchaForm(forms.Form):
    captcha = CaptchaField()


class ContactForm(forms.Form):
    subject = forms.CharField(max_length = 100)
    sender = forms.EmailField()
    message = forms.CharField(widget = forms.Textarea(attrs = {'class': 'form-control'}))
    copy = forms.BooleanField(required = False)

resume/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, render_to_response, redirect
from resume.models import MyUser
from django.core.urlresolvers import reverse
from django.contrib.auth.forms import AuthenticationForm
from admin import UserCreationForm, UserChangeForm
from django.contrib.auth import login, logout
from django.views.generic import FormView, View, TemplateView, UpdateView, DetailView, DeleteView
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseForbidden
from forms import CaptchaForm, ContactForm
from django.template import RequestContext
from django.core.mail import send_mail, BadHeaderError
from django.core.context_processors import csrf



class HomeView(TemplateView):
    template_name = 'resume/home.html'

class InfoView(TemplateView):
    template_name = 'resume/info.html'

   
class Login(FormView):
    form_class = AuthenticationForm
    success_url = '../'
    template_name = 'resume/login.html'

    def form_valid(self, form):
        user = form.get_user()
        login(self.request, user)
        return super(Login, self).form_valid(form)


class LogOut(View):
    success_url = '/regist/'
    template_name = 'resume/base.html'

    def get(self,request):
        logout(request)
        return HttpResponseRedirect('/login/')


class UserView(UpdateView):
    model = MyUser
    template_name = 'resume/change_info.html'
    success_url = '../../../../'
    fields = ['name', 'email', 'phone_number', 'date_of_birth', 'first_name', 'last_name', 'avatar']


def contactView(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        #Если форма заполнена корректно, сохраняем все введённые пользователем значения
        if form.is_valid():
            subject = form.cleaned_data['subject']
            sender = form.cleaned_data['sender']
            message = form.cleaned_data['message']
            copy = form.cleaned_data['copy']

            recipients = ['resume.my@yandex.ru']
            #Если пользователь захотел получить копию себе, добавляем его в список получателей
            if copy:
                recipients.append(sender)
            try:
                send_mail(subject, message, 'resume.my@yandex.ru', recipients)
            except BadHeaderError: #Защита от уязвимости
                return HttpResponse('Invalid header found')
            #Переходим на другую страницу, если сообщение отправлено
            return render(request, 'resume/thanks.html')
    else:
        #Заполняем форму
        form = ContactForm()
    #Отправляем форму на страницу
    return render(request, 'resume/contact.html', {'form': form})
   

class UserDelete(DeleteView):
    model = MyUser
    template_name = 'resume/del_user.html'
    success_url = '../../../../'

resume/templates/resume/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link href="{% static 'style.css' %}" rel="stylesheet" media="screen">
    <title>{% block title %}{% endblock %}</title>
</head>

<body>
    <div class="wrapper">
        <header>
            <nav>
                <ul>
                    {%if not user.is_authenticated %}
                        <li><button class="menu"><a href="{% url 'login' %}"><p class="menuname">Home</p></a></button></li>
                        <li><button class="menu"><a href="{% url 'contact' %}"><p class="menuname">Contact form</p></a></button></li>
                        <li>{% block header%}{%endblock%}</li>
                        <li><button class="menu"><a href="{% url 'registration_register' %}"><p class="menuname">Registration</p></a></button></li>              
                    {% else %}
                        <li><button class="menu"><a href="{% url 'home' %}"><p class="menuname">Home</p></a></button></li>
                        <li><button class="menu"><a href="{% url 'contact' %}"><p class="menuname">Contact form</p></a></button></li>
                        <li><button class="menu"><a href="{% url 'info' %}">Cabinet</a></button></li>
                        <li><button class="menu"><a href="{% url 'logout' %}"><p class="menuname">Exit</p></a></button></li>
                        <li><img src="/media/{{ user.avatar }}" id="avatar" align="left"></li>
                        <li id="infouser">{{user.first_name}} {{ user.last_name|make_list|first }}.</li>
                    {% endif %} 
                </ul>
            </nav>
        </header>
        <div class="content">
            {% block content %}{% endblock %}
        </div>
        <div id="buffer"></div>
    </div>
    <footer>
            <p id="footertext">&copy; Dmitriy Lizunov 2015</p>
    </footer>
</body>
</html>

resume/templates/resume/change_info.html
{% extends "resume/base.html" %}

{% block title %}Personal{% endblock %}

{% block content %}
<form role="form" action='' method='post' enctype="multipart/form-data">{% csrf_token %}
    <div id="changeinfo">
        <div class="infofield">
            {{ form.name.errors }}
            <label class="infolabel">Name:</label>
            {{ form.name }}
        </div>
        <div class="infofield">{{ form.first_name.errors }}
            <label class="infolabel">Frist name:</label>
            {{ form.first_name }}
        </div>
        <div class="infofield">{{ form.last_name.errors }}
            <label class="infolabel">Last name:</label>
            {{ form.last_name }}
        </div>
        <div class="infofield">{{ form.email.errors }}
            <label class="infolabel">E-mail:</label>
            {{ form.email }}
        </div>
        <div class="infofield">{{ form.phone_number.errors }}
            <label class="infolabel">Phone:</label>
            {{ form.phone_number }}
        </div>
        <div class="infofield">{{ form.date_of_birth.errors }}
            <label class="infolabel">Date of birth(YYYY-MM-DD):</label>
            {{ form.date_of_birth }}
        </div>
        <div class="infofield">
            <label class="infolabel">Avatar:</label>
            <input type="file" enctype="multipart/form-data" name="avatar" >{{user.avatar}}</input>
        </div>

        <button type="submit" class="confirm" value="Send">Send</button>
        <button><a href="del_user/">Delete</a></button>
    </div>
</form>
{% endblock %}

resume/templates/resume/contact.html
{% extends "resume/base.html" %}

{% block title %}Send mail{% endblock %}

{% block content %}
<form action="/contact/" method="post">{% csrf_token %}
    {{ form.non_field_errors }}
    <div id="conmain">
        <div class="confield">
            <label for="id_subject" class="conlabel">Тема:</label>
            {{ form.subject.errors }}
            {{ form.subject }}
        </div>
        <div class="confield">
            <label for="id_sender" class="conlabel">E-mail:</label>
            {{ form.sender.errors }}
            {{ form.sender }}
        </div>
        <div class="confield">
            <label for="id_message" class="conlabel">Сообщение:</label>
            {{ form.message.errors }}
            {{ form.message }}
        </div>
        <div class="confield">
            {{ form.copy.errors }}
            <label for="id_copy" class="conlabel">Отправить копию себе {{ form.copy }}</label>
        </div>
        <input type="submit" value="Отправить" class="confirm">
    </div>
</form>
 {% endblock %}

resume/templates/resume/del_user.html
{% extends 'resume/base.html' %}

{% block title %}Delete{% endblock %}
 
{% block content %}
<form method="POST" action='' enctype="multipart/form-data">
    {% csrf_token %}
    <div id="delete">
        <p>Delete user?</p>
        <input type="submit" class="confirm" value="Delete" />
        <button><a href="{% url 'home' %}">Back</a></button>     
    </div>
</form>          
{% endblock %}

resume/templates/resume/home.html
{% extends "resume/base.html" %}

{% block title %}Home{% endblock %}
{% block content %}
<h1>Лизунов Дмитрий Сергеевич</h1>
<img id="photo" src="/media/dima.png" alt="">
<p class="titlename">Дата рождения:</p>25 февраля 1993 года (22 года)
<p class="titlename">Гражданство:</p> Украина
<p class="titlename">Семейное положение:</p> не женат
<p class="titlename">Телефон:</p> +38-096-938-79-00
<p class="titlename">Эл. почта:</p> DimaLizunov@gmail.com

<h2 id="education">Образование:</h2>
<p>2010 – 2014, Запорожский национальный технический университет, факультет радиоэлектроники и телекоммуникаций, специальность – системы технической защиты информации, квалификация: бакалавр (диплом с отличием).<br>
2014 – настоящее время, Запорожский национальный технический университет, факультет радиоэлектроники и телекоммуникаций, специальность – системы технической защиты информации, квалификация: магистр.<br>
Опыт работы:
16.04.2015 – 30.06.2015, старший лаборант кафедры защиты информации ЗНТУ.<p>
<h2>Умения и навыки:</h2>
<p>Знание языков: русский, украинский - свободно, английский – средний (на уровне чтения технической документации).<br>
Применяю HTML5, CSS3 для решения различного рода задач. Обладаю базовыми знаниями ООП. Самостоятельно изучаю Django и Python (есть программные комплексы «Заметки» и «Резюме»).</p>
<h2>Личные качества:</h2> 
<p>Коммуникабельность, обучаемость, стрессоустойчивость, креативность, пунктуальность, инициативность, желание развиваться.</p>
{% endblock %}}

resume/templates/resume/info.html
{% extends "resume/base.html" %}

{% block title %}Info{% endblock %}

{% block content %}
<div id="info">
  <h3>Please, enter your button:</h3>
  <div>
     <button><a href="{% url 'change_info' pk=user.pk %}">Personal information</a></button>
     <button><a href="{% url 'auth_password_change' %}">Change password</a></button>
     </div>
</div>
 {% endblock %}

resume/templates/resume/login.html
{% extends "resume/base.html" %}

{% block title %}Log In{% endblock %}
{% block header%}
<form role="form" action='' method='post' class="menu" id="login">{% csrf_token %}
    <label  for="username" value="login">Login: </label>{{ form.username }}
    <label  for="pass">Password: </label>{{ form.password }}
    <button type="submit" value="Send" id="send">Send</button>
</form>

 {%endblock%}

 {% block content %}
<h1>Лизунов Дмитрий Сергеевич</h1>
<img id="photo" src="/media/dima.png" alt="">
<p class="titlename">Дата рождения:</p>25 февраля 1993 года (22 года)
<p class="titlename">Гражданство:</p> Украина
<p class="titlename">Семейное положение:</p> не женат
<p class="titlename">Телефон:</p> +38-096-938-79-00
<p class="titlename">Эл. почта:</p> DimaLizunov@gmail.com

<h2 id="education">Образование:</h2>
<p>2010 – 2014, Запорожский национальный технический университет, факультет радиоэлектроники и телекоммуникаций, специальность – системы технической защиты информации, квалификация: бакалавр (диплом с отличием).<br>
2014 – настоящее время, Запорожский национальный технический университет, факультет радиоэлектроники и телекоммуникаций, специальность – системы технической защиты информации, квалификация: магистр.<br>
Опыт работы:
16.04.2015 – 30.06.2015, старший лаборант кафедры защиты информации ЗНТУ.<p>
<h2>Умения и навыки:</h2>
<p>Знание языков: русский, украинский - свободно, английский – средний (на уровне чтения технической документации).<br>
Применяю HTML5, CSS3 для решения различного рода задач. Обладаю базовыми знаниями ООП. Самостоятельно изучаю Django и Python (есть программные комплексы «Заметки» и «Резюме»).</p>
<h2>Личные качества:</h2> 
<p>Коммуникабельность, обучаемость, стрессоустойчивость, креативность, пунктуальность, инициативность, желание развиваться.</p>
{% endblock %}}

resume/templates/resume/thanks.html
{% extends "resume/base.html" %}

{% block title %}Success{% endblock %}

{% block content %}
<p class="success">Successful</p>
 {% endblock %}